### ISSUE TITLE
Make setup.py install dependencies

### ISSUE THREAD

**Issue by zakiali** [HERA-Team/aipy#1]

**Comment by SaulAryehKohn** [comment]
ez_setup.py should nominally do this, but it's dated. I will get round to updating this soon.

**Comment by pkgw** [comment]
In general, the current `setup.py` script is quite dated and could stand to be updated. Something like [the astropy setup.py](https://github.com/astropy/astropy/blob/master/setup.py) is probably a good template to look at.

**Comment by SaulAryehKohn** [comment]
What was the conclusion on pyephem vs. astropy? Are we phasing pyephem out actively, or is that more of a future goal?

**Comment by jpober** [comment]
Astropy is lacking the ephemeris capabilities of pyephem, so I think it's here to stay in some capacity.

**Comment by pkgw** [comment]
[Skyfield](http://rhodesmill.org/skyfield/) looks to be @brandon-rhodes's replacement for pyephem, and it looks like it is more modern, careful about UTC, etc. So if we're actively interested in swapping out the latter, it might be what we want to use.

**Comment by brandon-rhodes** [comment]
I do intend for Skyfield to be the recommended library going forward! I just need to finish adding in all of the features (sunrise / sunset, etc) that PyEphem provided in its C code. But Skyfield is already far more accurate than PyEphem and is good at providing positions.

**Comment by AaronParsons** [comment]
It looks like Skyfield v1.0 was released in March, 2017, so that is probably a signal that we should start porting!
