### ISSUE TITLE
PyPI package is old

### ISSUE THREAD

**Issue by steven-murray** [HERA-Team/aipy#55]
The latest PyPI package seems to be v2.1.12, compared to conda being 3.0.0rc2. 

This is creating a few problems with dependencies, particularly `astropy`, which has a fairly old restriction in the 2.x version. 

It would be great to update the PyPI version!

**Comment by pkgw** [comment]
3.0.0rc2 is actually available on PyPI as a prerelease:

https://pypi.org/project/aipy/3.0.0rc2/

So I believe that with the right flags you should be able to get `pip` to install it. However, that prerelease has been out for a long time at this point ... we should probably just make it official and call it 3.0.0.

**Comment by steven-murray** [comment]
Ah, OK. Interesting -- so PyPI won't try to install an rc version unless forced to, while `conda` will. I'll change the flags!

**Comment by adampbeardsley** [comment]
After reading some backlog conversation on the herasoftware slack channel, looks like this is the same as the issue I just posted (#56). Who has permission to make 3.0.0 official? @pkgw @AaronParsons ?

**Comment by pkgw** [comment]
@adampbeardsley I believe that I have the technical permissions, but I'd want to get the OK from @AaronParsons first.

**Comment by steven-murray** [comment]
OK, so I just checked the actual `setup.py` at https://pypi.org/project/aipy/3.0.0rc2/, and it does *not* have the conditional that chooses between py2 and py3 -- it is hard-coded to depend on `'astropy>=1.0, <2.0'`, which will definitely fail for py3. That makes bumping the PyPI version very urgent.

**Comment by pkgw** [comment]
The Astropy version constraint was given by the person who contributed the port of AIPY to Python 3 — he said that it didn't work with Astropy >= 2. Unfortunately I don't recall what the issue was. Given where things are, I think the pretty clear path forward is to relax that requirement and figure out fixes for any breakages related to newer Astropys if and when they are uncovered.

(That being said ... I have trouble imagining that the incompatibility was the sort of thing that would lead to subtly wrong science results rather than code crashes, but maybe it is!)

**Comment by steven-murray** [comment]
Hmmm. That is strange. Astropy >=3 certainly doesn't seem to break aipy (in any use case I've found) on py3.

**Comment by jsdillon** [comment]
@pkgw @adampbeardsley Just bugged @AaronParsons about this. He said it's fine. Also he's in favor of adding someone new to have the permissions for aipy on PyPI. @plaplant was nominated on today's pyuvdata telecon and both he and @AaronParsons are fine with that. @pkgw can you extend permissions to @plaplant?

**Comment by pkgw** [comment]
@jsdillon Looks like I have permissions to make new releases but not to manage the list of project maintainers — @AaronParsons will have to do that personally.

**Comment by jaycedowell** [comment]
> The Astropy version constraint was given by the person who contributed the port of AIPY to Python 3 — he said that it didn't work with Astropy >= 2. Unfortunately I don't recall what the issue was.

This may be a little late but the whole `'astropy>=1.0, <2.0'` thing is/was about maintaining compatibility with Python2 (astropy dropped support for it starting with version 2.0).  If Python2 support doesn't matter then the version of astropy is flexible.

**Comment by pkgw** [comment]
@jaycedowell Thanks, that's helpful. In that case we should be totally OK to relax that constraint.

**Comment by adampbeardsley** [comment]
@pkgw I think this is still open? Are you able to bump the version on PyPI?

**Comment by pkgw** [comment]
@adampbeardsley I do have permissions to upload a new version. To make this sustainable we need an intervention from @AaronParsons on PyPI to give @plaplant ownership and myself privileges on the package, though.

**Comment by plaplant** [comment]
@pkgw can you upload a new version in this one instance? @AaronParsons is away right now, and the astropy version constraints are stalling our builds for dependencies. We should have things in a more sustainable configuration sometime next week.

**Comment by pkgw** [comment]
OK, I've tidied up the current repo and published 3.0.1.

**Comment by plaplant** [comment]
Thanks so much @pkgw!
