### ISSUE TITLE
confused requirements?

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/aipy#56]
Trying to hunt down why hera_qm is suddenly failing on master:
https://travis-ci.org/HERA-Team/hera_qm/jobs/556686251
Notably, this shows up at the end of the output after the command to install uvtools:
```
ERROR: pyuvdata 1.4.0 has requirement astropy>=2.0, but you'll have astropy 1.3.3 which is incompatible.
Installing collected packages: uvtools, pyephem, astropy
  Found existing installation: astropy 3.2.1
    Uninstalling astropy-3.2.1:
      Successfully uninstalled astropy-3.2.1
Successfully installed astropy-1.3.3 pyephem-3.7.6.0 uvtools-0.1.0
```
Ok, so something's going on with uvtools causing astropy to get downgraded.
The only requirements for uvtools are numpy, six, scipy, and aipy>=3.0rc2.
The best we can figure is that aipy's astropy requirement is somehow getting mixed up. The environment already meets the aipy requirement, but @steven-murray suggests pip will still check its requirements. 
Notably this may have only started to appear because of the recent changes to uvtool's `setup.py` (HERA-Team/uvtools#40)

**Comment by adampbeardsley** [comment]
Update to remove a variable:
I started a fresh environment running python 3.7. I followed the travis.yml for hera_qm up to but not including installing uvtools. At this point I had aipy==3.0.0rc2 and astropy==3.2.1.
I then tried running `pip install aipy==3.0.0rc2`, which in theory should do nothing? Instead it tried to downgrade my astropy:
`Collecting astropy<2.0,>=1.0 (from aipy==3.0.0rc2)`

**Comment by steven-murray** [comment]
Can probably close this as the same as #55
